#define TFPI x_rdata[0]
#define VIIa_TF x_rdata[1]
#define VIIa_TF_X x_rdata[2]
#define VIIa_TF_Xa x_rdata[3]
#define X x_rdata[4]
#define Xa x_rdata[5]
#define Xa_TFPI x_rdata[6]
#define Xa_TFPI_VIIa_TF x_rdata[7]