#define dxdotdw0 dxdotdw[0]
#define dxdotdw1 dxdotdw[1]
#define dxdotdw2 dxdotdw[2]
#define dxdotdw3 dxdotdw[3]
#define dxdotdw4 dxdotdw[4]
#define dxdotdw5 dxdotdw[5]
#define dxdotdw6 dxdotdw[6]
#define dxdotdw7 dxdotdw[7]